### ISSUE TITLE
will work with c9/core?

### ISSUE THREAD

**Issue by juanitomint** [AVGP/cloud9hub#22]
Cloud9 has released the version they have working at c9.io in https://github.com/c9/core
Would cloud9hub be working with the new platform?
keep on the good job! 
thanks!

**Comment by thetomester13** [comment]
Bump. Would love to see this working. Right now I'm just forwarded to a blank dashboard page...

**Comment by Harjot1Singh** [comment]
I'm currently trying to update it - is this project dead or does the author still accept pulls? Otherwise I might just write my own soon that supports the c9 v3

**Comment by AVGP** [comment]
Hey Harjot,

that's terrific! This project is alive but I don't find the time this thing
deserves. If you'd like to maintain the project in the future, I'd be more
than happy to transfer!

Great to see that there's a great community willing to run Cloud9 on their
own hardware! <3

Let me know if I can do something to help
Martin


2015-12-05 3:15 GMT+01:00 Harjot Singh <notifications@github.com>:

**Comment by Harjot1Singh** [comment]
I've updated it to something that works, but the interface is a bit broken, I think I'll do a complete rewrite for v3 since a lot of the fixes are patchwork etc

**Comment by Harjot1Singh** [comment]
For those who want to try it, curl https://raw.githubusercontent.com/harjot1singh/cloud9hub/master/install.sh | sh

**Comment by AVGP** [comment]
@Harjot1Singh That is so great! It does look like you should be the future maintainer, if you'd like :-)

**Comment by Harjot1Singh** [comment]
@AVGP I'd be happy to be the future maintainer
